language: node_js

stages:
  - name: script
    # Require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master

script:
  # run formatting check on PR builds
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/validate-formatting.sh; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn test; fi'
  # Test a production build on PR builds as well as master merges, to catch deployment issues before merging of PRs
  - yarn build:prefix

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./public
  github-url: github.ibm.com
  on:
    branch: master
